server:
  port: 1000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zrf
spring:
  profiles:
    active: local
#  jackson:
#    default-property-inclusion: non_null
